version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ./config/.local.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volume/postgres/:/var/lib/postgresql
    networks:
      base_network:


networks:
  base_network:
