version: '3.7'

services:
  frontoffice:
    build:
      context: ./
      dockerfile: ./deploy/frontoffice/Dockerfile.local
    networks:
      base_network:
    ports:
      - '80:80'
  backoffice:
    build:
      context: ./
      dockerfile: ./deploy/backoffice/Dockerfile.local
    networks:
      base_network:
    ports:
      - '8080:80'
  api:
    build:
      context: ./
      dockerfile: ./deploy/api/Dockerfile.local
    networks:
      base_network:
    ports:
      - '3333:3333'
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./volume/postgres/:/var/lib/postgresql
    networks:
      base_network:


networks:
  base_network:
