version: '3.7'

services:
  frontoffice:
    build:
      context: ./
      dockerfile: ./deploy/frontoffice/Dockerfile.local
    networks:
      - overlay
    ports:
      - '80:80'
  backoffice:
    build:
      context: ./
      dockerfile: ./deploy/backoffice/Dockerfile.local
    networks:
      - overlay
    ports:
      - '8080:80'
  postgres:
    image: "postgres:10-alpine"
    hostname: "postgres"
    networks:
      - overlay
    environment:
      POSTGRES_PASSWORD: ilt0q1drzye
      POSTGRES_USER: postgres
      POSTGRES_DB: api_local
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_data_vol:/var/lib/postgresql/data'
  api:
    build:
      context: ./
      dockerfile: ./deploy/api/Dockerfile
    hostname: api
    networks:
      - overlay
    environment:
      POSTGRES_HOST: postgres
    ports:
      - '3333:3333'


volumes:
  postgres_data_vol:
  redis_data:
  minio-data:
  pgadmin:
networks:
  overlay:

